# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import processor_pb2 as processor__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessorServiceStub:
    """============================================================================
    Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/mem.worker.v1.ProcessorService/Process',
                request_serializer=processor__pb2.ProcessRequest.SerializeToString,
                response_deserializer=processor__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/mem.worker.v1.ProcessorService/Chat',
                request_serializer=processor__pb2.ChatRequest.SerializeToString,
                response_deserializer=processor__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/mem.worker.v1.ProcessorService/HealthCheck',
                request_serializer=processor__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=processor__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ProcessorServiceServicer:
    """============================================================================
    Service
    ============================================================================

    """

    def Process(self, request, context):
        """Process a single file end-to-end:
        1. Resolve storage_uri -> bytes
        2. Route to a Processor by mime
        3. Run the Processor + Provider(s)
        4. Return a ProcessResponse with everything needed to persist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Retired compatibility slot. Implementations MUST return UNIMPLEMENTED;
        final reasoning and answer generation belong to the external Agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Liveness / readiness probe. Always cheap. Does NOT require external
        services (Ollama, S3) to be reachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=processor__pb2.ProcessRequest.FromString,
                    response_serializer=processor__pb2.ProcessResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=processor__pb2.ChatRequest.FromString,
                    response_serializer=processor__pb2.ChatResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=processor__pb2.HealthCheckRequest.FromString,
                    response_serializer=processor__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mem.worker.v1.ProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mem.worker.v1.ProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessorService:
    """============================================================================
    Service
    ============================================================================

    """

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.worker.v1.ProcessorService/Process',
            processor__pb2.ProcessRequest.SerializeToString,
            processor__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.worker.v1.ProcessorService/Chat',
            processor__pb2.ChatRequest.SerializeToString,
            processor__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.worker.v1.ProcessorService/HealthCheck',
            processor__pb2.HealthCheckRequest.SerializeToString,
            processor__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
